# Generated by Django 6.0.3 on 2026-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microoganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('habitat', models.CharField(max_length=250)),
                ('morphology', models.TextField()),
                ('biochemicals', models.TextField()),
                ('metabolism', models.CharField(max_length=250)),
                ('diseases', models.TextField()),
                ('antibiotics', models.TextField()),
            ],
        ),
    ]
